package texteditor;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.*;
//import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Juliet
 */
public class MainFrme extends javax.swing.JFrame {

    File selectedFile = null;
    
    public MainFrme() {
        initComponents();
        
        //Filter Files to display
        //Set JFileChooser to accept only text files
        FileNameExtensionFilter filter = new FileNameExtensionFilter("TEXT FILES", "txt", "text");
        fileOpener.setFileFilter(filter);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileOpener = new javax.swing.JFileChooser();
        saveDialog = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTextArea = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        OpenBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();

        saveDialog.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        saveDialog.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java Text Editor");
        setLocation(new java.awt.Point(280, 150));

        displayTextArea.setColumns(20);
        displayTextArea.setRows(5);
        jScrollPane1.setViewportView(displayTextArea);

        jToolBar1.setRollover(true);

        OpenBtn.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        OpenBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texteditor/open_new_file.png"))); // NOI18N
        OpenBtn.setBorder(null);
        OpenBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        OpenBtn.setFocusable(false);
        OpenBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        OpenBtn.setLabel("Open");
        OpenBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        OpenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(OpenBtn);

        SaveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/texteditor/Save_icon.png"))); // NOI18N
        SaveBtn.setText("Save");
        SaveBtn.setBorder(null);
        SaveBtn.setFocusable(false);
        SaveBtn.setHideActionText(true);
        SaveBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SaveBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(SaveBtn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
       
        //if we are editing an opened file,then we have to save the contents on the same fil, selectedFile
        if(selectedFile != null) {
            //show Save dialog and directory
            try {
                PrintWriter printWriter = new PrintWriter(selectedFile);
                printWriter.write(displayTextArea.getText());
                printWriter.close();
                JOptionPane.showMessageDialog(rootPane, "File Saved!", "Done", JOptionPane.INFORMATION_MESSAGE);
            }
            catch (FileNotFoundException e) {
                Logger.getLogger(MainFrme.class.getName()).log(Level.SEVERE, null, e);
            }
        } 
        
        else {
            int status = saveDialog.showOpenDialog(rootPane);
            if(status == JFileChooser.APPROVE_OPTION){
               
               //directroy gotten. display filename
               String fileName = JOptionPane.showInputDialog("File Name", "Untitled.txt");
               
               if(!fileName.contains(".txt")) {
                   fileName += ".txt";
               }
               
                File file = new File(saveDialog.getSelectedFile() + "\\" + fileName);
                
                if(file.exists()) {
                     JOptionPane.showMessageDialog(rootPane, "File Already in Existence.", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    
                    try {
                        file.createNewFile();
                        PrintWriter printWriter = new PrintWriter(file);
                        printWriter.write(displayTextArea.getText());
                        printWriter.close();
                        JOptionPane.showMessageDialog(rootPane, "File Saved!", "Done", JOptionPane.INFORMATION_MESSAGE);
                    }
                    catch (IOException ex) {
                       Logger.getLogger(MainFrme.class.getName()).log(Level.SEVERE, null, ex);
                   }
                   
                }
            } else {
                    JOptionPane.showMessageDialog(rootPane, "Error Occured", "Cannot Save File", JOptionPane.ERROR_MESSAGE);
                     return;
            }
        }
        
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void OpenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenBtnActionPerformed
       
        //show file opener dialogue here
        int status = fileOpener.showOpenDialog(rootPane);
        if (status == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileOpener.getSelectedFile();
            System.out.println("File chosen. File name = " + fileOpener.getSelectedFile().getName());
            
            try {
                //Now read the contents of the selected file
                Scanner scanner = new Scanner(new FileInputStream(selectedFile));
                String buffer = "";
                while(scanner.hasNext()) {
                    buffer += scanner.nextLine() + "\n";
                } 
                displayTextArea.setText(buffer);
            } 
            catch (FileNotFoundException ex) {
                Logger.getLogger(MainFrme.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            System.out.println("No File Selected");
        }
    }//GEN-LAST:event_OpenBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OpenBtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextArea displayTextArea;
    private javax.swing.JFileChooser fileOpener;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JFileChooser saveDialog;
    // End of variables declaration//GEN-END:variables
}
